# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# NOTE: grpc_tools generates bare "import hub_pb2" — must be "from . import hub_pb2" for package use.
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hub_pb2 as hub__pb2

GRPC_GENERATED_VERSION = '1.64.3'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class HubServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateHub = channel.unary_unary(
                '/meridian.hub.v1.HubService/CreateHub',
                request_serializer=hub__pb2.CreateHubRequest.SerializeToString,
                response_deserializer=hub__pb2.CreateHubResponse.FromString,
                _registered_method=True)
        self.TerminateHub = channel.unary_unary(
                '/meridian.hub.v1.HubService/TerminateHub',
                request_serializer=hub__pb2.TerminateHubRequest.SerializeToString,
                response_deserializer=hub__pb2.TerminateHubResponse.FromString,
                _registered_method=True)
        self.JoinHub = channel.stream_stream(
                '/meridian.hub.v1.HubService/JoinHub',
                request_serializer=hub__pb2.JoinHubRequest.SerializeToString,
                response_deserializer=hub__pb2.JoinHubEvent.FromString,
                _registered_method=True)
        self.TapHub = channel.unary_unary(
                '/meridian.hub.v1.HubService/TapHub',
                request_serializer=hub__pb2.TapHubRequest.SerializeToString,
                response_deserializer=hub__pb2.TapHubResponse.FromString,
                _registered_method=True)
        self.CreateCheckpoint = channel.unary_unary(
                '/meridian.hub.v1.HubService/CreateCheckpoint',
                request_serializer=hub__pb2.CreateCheckpointRequest.SerializeToString,
                response_deserializer=hub__pb2.CreateCheckpointResponse.FromString,
                _registered_method=True)
        self.RollbackCheckpoint = channel.unary_unary(
                '/meridian.hub.v1.HubService/RollbackCheckpoint',
                request_serializer=hub__pb2.RollbackCheckpointRequest.SerializeToString,
                response_deserializer=hub__pb2.RollbackCheckpointResponse.FromString,
                _registered_method=True)
        self.HubStatus = channel.unary_unary(
                '/meridian.hub.v1.HubService/HubStatus',
                request_serializer=hub__pb2.HubStatusRequest.SerializeToString,
                response_deserializer=hub__pb2.HubStatusResponse.FromString,
                _registered_method=True)
        self.DetectFork = channel.unary_unary(
                '/meridian.hub.v1.HubService/DetectFork',
                request_serializer=hub__pb2.DetectForkRequest.SerializeToString,
                response_deserializer=hub__pb2.DetectForkResponse.FromString,
                _registered_method=True)
        self.DecideFork = channel.unary_unary(
                '/meridian.hub.v1.HubService/DecideFork',
                request_serializer=hub__pb2.DecideForkRequest.SerializeToString,
                response_deserializer=hub__pb2.DecideForkResponse.FromString,
                _registered_method=True)
        self.AgentStream = channel.stream_stream(
                '/meridian.hub.v1.HubService/AgentStream',
                request_serializer=hub__pb2.AgentMessage.SerializeToString,
                response_deserializer=hub__pb2.AgentMessage.FromString,
                _registered_method=True)
        self.OrchestratorEvents = channel.stream_stream(
                '/meridian.hub.v1.HubService/OrchestratorEvents',
                request_serializer=hub__pb2.OrchEvent.SerializeToString,
                response_deserializer=hub__pb2.OrchEvent.FromString,
                _registered_method=True)


class HubServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateHub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateHub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinHub(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TapHub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HubStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecideFork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgentStream(self, request_iterator, context):
        """Bidirectional streaming RPC for agent-to-hub message exchange.

        Accepts a stream of AgentMessage frames from a connected agent and
        returns a stream of AgentMessage frames back, allowing full-duplex
        communication between an agent and the hub.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrchestratorEvents(self, request_iterator, context):
        """Bidirectional streaming RPC for orchestrator event exchange.

        Accepts a stream of OrchEvent frames from the orchestrator and returns
        a stream of OrchEvent frames back, enabling the hub to relay lifecycle
        and status events to and from the orchestrator in real time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateHub': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateHub,
                    request_deserializer=hub__pb2.CreateHubRequest.FromString,
                    response_serializer=hub__pb2.CreateHubResponse.SerializeToString,
            ),
            'TerminateHub': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateHub,
                    request_deserializer=hub__pb2.TerminateHubRequest.FromString,
                    response_serializer=hub__pb2.TerminateHubResponse.SerializeToString,
            ),
            'JoinHub': grpc.stream_stream_rpc_method_handler(
                    servicer.JoinHub,
                    request_deserializer=hub__pb2.JoinHubRequest.FromString,
                    response_serializer=hub__pb2.JoinHubEvent.SerializeToString,
            ),
            'TapHub': grpc.unary_unary_rpc_method_handler(
                    servicer.TapHub,
                    request_deserializer=hub__pb2.TapHubRequest.FromString,
                    response_serializer=hub__pb2.TapHubResponse.SerializeToString,
            ),
            'CreateCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCheckpoint,
                    request_deserializer=hub__pb2.CreateCheckpointRequest.FromString,
                    response_serializer=hub__pb2.CreateCheckpointResponse.SerializeToString,
            ),
            'RollbackCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackCheckpoint,
                    request_deserializer=hub__pb2.RollbackCheckpointRequest.FromString,
                    response_serializer=hub__pb2.RollbackCheckpointResponse.SerializeToString,
            ),
            'HubStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.HubStatus,
                    request_deserializer=hub__pb2.HubStatusRequest.FromString,
                    response_serializer=hub__pb2.HubStatusResponse.SerializeToString,
            ),
            'DetectFork': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFork,
                    request_deserializer=hub__pb2.DetectForkRequest.FromString,
                    response_serializer=hub__pb2.DetectForkResponse.SerializeToString,
            ),
            'DecideFork': grpc.unary_unary_rpc_method_handler(
                    servicer.DecideFork,
                    request_deserializer=hub__pb2.DecideForkRequest.FromString,
                    response_serializer=hub__pb2.DecideForkResponse.SerializeToString,
            ),
            'AgentStream': grpc.stream_stream_rpc_method_handler(
                    servicer.AgentStream,
                    request_deserializer=hub__pb2.AgentMessage.FromString,
                    response_serializer=hub__pb2.AgentMessage.SerializeToString,
            ),
            'OrchestratorEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.OrchestratorEvents,
                    request_deserializer=hub__pb2.OrchEvent.FromString,
                    response_serializer=hub__pb2.OrchEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meridian.hub.v1.HubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meridian.hub.v1.HubService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HubService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateHub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.hub.v1.HubService/CreateHub',
            hub__pb2.CreateHubRequest.SerializeToString,
            hub__pb2.CreateHubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateHub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.hub.v1.HubService/TerminateHub',
            hub__pb2.TerminateHubRequest.SerializeToString,
            hub__pb2.TerminateHubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinHub(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/meridian.hub.v1.HubService/JoinHub',
            hub__pb2.JoinHubRequest.SerializeToString,
            hub__pb2.JoinHubEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TapHub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.hub.v1.HubService/TapHub',
            hub__pb2.TapHubRequest.SerializeToString,
            hub__pb2.TapHubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.hub.v1.HubService/CreateCheckpoint',
            hub__pb2.CreateCheckpointRequest.SerializeToString,
            hub__pb2.CreateCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.hub.v1.HubService/RollbackCheckpoint',
            hub__pb2.RollbackCheckpointRequest.SerializeToString,
            hub__pb2.RollbackCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HubStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.hub.v1.HubService/HubStatus',
            hub__pb2.HubStatusRequest.SerializeToString,
            hub__pb2.HubStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.hub.v1.HubService/DetectFork',
            hub__pb2.DetectForkRequest.SerializeToString,
            hub__pb2.DetectForkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecideFork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meridian.hub.v1.HubService/DecideFork',
            hub__pb2.DecideForkRequest.SerializeToString,
            hub__pb2.DecideForkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgentStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/meridian.hub.v1.HubService/AgentStream',
            hub__pb2.AgentMessage.SerializeToString,
            hub__pb2.AgentMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrchestratorEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/meridian.hub.v1.HubService/OrchestratorEvents',
            hub__pb2.OrchEvent.SerializeToString,
            hub__pb2.OrchEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
